[build]
  command = "cd ng-hotel && npm install && npm run build -- --configuration=production && cd ../xp-hotel && npm install"
  publish = "ng-hotel/dist/ng-hotel/browser"

[functions]
  directory = "netlify/functions"

# Cette redirection API doit être AVANT la redirection SPA
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200